[package]
name = "blockchain_marco"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
ring = "0.16.20"
hex = "0.4"
warp = "0.3"

